apiVersion: v1
kind: Service
metadata:
    name: init-service
    namespace: "heat-scheduling"
spec:
    ports:
      -
         port: 80
         targetPort: 8090
    selector:
      sel: init
    type: "LoadBalancer"
