apiVersion: v1
kind: Pod
metadata:
    name: heat-scheduler-extdr
    namespace: kube-system
    labels:
        sel: heat-scheduler-extdr
spec:
    containers:
        - name: heat-scheduler-extdr
          image: borismattijssen/simpleserver
          # image: gcr.io/nce-dsd2015/heat-scheduler-extender:1.0.0
          ports:
            - containerPort: 8002
    restartPolicy: "Always"
