apiVersion: v1
kind: Pod
metadata:
    name: heat-scheduler-extdr
    namespace: heat-scheduling
    labels:
        sel: heat-scheduler-extdr
spec:
    containers:
        - name: heat-scheduler-extdr
          image: gcr.io/bep-matosi/heat-scheduler-extender:1.0.0
          ports:
            - containerPort: 8100
    restartPolicy: "Always"
