
apiVersion: v1
kind: Service
metadata:
    name: scheduler-extender-svc
spec:
    ports:
      -
         port: 80
         targetPort: 8100
    selector:
      sel: scheduler-extender
    type: "LoadBalancer"
