apiVersion: v1
kind: Service
metadata:
    name: heat-scheduler-extdr-svc
spec:
    ports:
      -
         port: 80
         targetPort: 8002
    selector:
      sel: heat-scheduler-extdr
    type: "LoadBalancer"
