apiVersion: v1
kind: Pod
metadata:
  name: aa
  annotations:
    scheduler.alpha.kubernetes.io/name: heat-scheduler
  labels:
    name: multischeduler-example
spec:
  containers:
  - name: pod-with-second-annotation-container
    image: gcr.io/google_containers/pause:2.0
