apiVersion: v1
kind: Pod
metadata:
  name: "monitor"
spec:
  containers:
    - name: "monitor"
      # image: "gcr.io/nce-dsd2015/monitor:1.0.9"
      image: "borismattijssen/nlz-heat"
      imagePullPolicy: Always
  restartPolicy: "Always"
