apiVersion: apps/v1beta2
kind: Deployment
metadata:
  labels:
    component: scheduler
    tier: control-plane
    app: heat-scheduler
  name: heat-scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: heat-scheduler
  template:
    metadata:
      labels:
        component: scheduler
        tier: control-plane
        app: heat-scheduler
        version: second
    spec:
      serviceAccountName: super
      containers:
      - command: [/usr/local/bin/kube-scheduler, --address=0.0.0.0, --v=5,
                  --scheduler-name=heat-scheduler, --policy-config-file=policy-config-file.json]
        image: borismattijssen/heat-scheduler:0.2.1
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /healthz
            port: 10251
          initialDelaySeconds: 15
        name: heat-scheduler
        readinessProbe:
          httpGet:
            path: /healthz
            port: 10251
        resources:
          requests:
            cpu: '0.1'
        securityContext:
          privileged: false
        volumeMounts: []
      hostNetwork: false
      hostPID: false
      volumes: []
